name: Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: zmkfirmware/zmk-build-arm:stable
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: West Init
        run: west init -l config
      - name: West Update
        run: west update
      - name: West Build
        run: west build -s zmk/app -b seeeduino_xiao_ble -- -DSHIELD=custom -DZMK_CONFIG="${GITHUB_WORKSPACE}/config"
      - name: Upload firmware
        uses: actions/upload-artifact@v4
        with:
          name: firmware
          path: build/zephyr/zmk.uf2
